name: Axe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  axe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the project
        run: npm run dev & npx wait-on http://localhost:5173/

      - name: Run Axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:5173/ --exit
