name: Pa11y-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pa11y-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the project
        run: npm run dev & npx wait-on http://localhost:5173/accessibility-integration

      - name: Run pa11y-ci
        run: |
          npm install -g pa11y-ci
          pa11y-ci
