name: Pa11y

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the project
        run: npm run dev & npx wait-on http://localhost:5173/

      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:5173/
